services:
  - type: web
    name: Univest-MIS-Dashboard
    runtime: node
    buildCommand: cd auditai/frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node auditai/backend/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
