services:
  - type: web
    name: Univest-MIS-Dashboard
    runtime: node
    rootDir: auditai
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: node backend/server.js
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
